# Generated by Django 4.0.3 on 2022-04-10 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_team1_delete_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team1',
        ),
    ]
